version: 0.2

phases:
  pre_build:
    commands:
      - chmod +x gradlew
      - echo "Starting Gradle build to package the application..."
      - ./gradlew clean build
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo "Building the Docker image..."
      - IMAGE_TAG=latest
      - IMAGE_REPO_NAME=taf/datastore-repo # Replace with your repository name
      - REPOSITORY_URI=.dkr.ecr.us-east-1.amazonaws.com
      - AWS_REGION=us-east-1
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Tagging the Docker image..."
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Writing image definitions..."
      - DOCKER_CONTAINER_NAME=tafdatastore
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - build/libs/*.jar
